#!/usr/bin/env bash
set -x

python -m tt.main \
create \
bank-salad-expense-transaction \
-f ./data/active/account0000-2024-11-14.xlsx \
-u user1

python -m tt.main \
create \
bank-salad-expense-transaction \
-f ./data/active/account0001-2024-11-16.xlsx \
-u user1

python -m tt.main \
create \
bank-salad-expense-transaction \
-f ./data/active/account0000-2024-11-29.xlsx \
-u user1
