#!/usr/bin/env bash
set -x
uv run -m tt.main \
get \
simple-transaction \

uv run -m tt.main \
get \
simple-transaction \
--symbol IVV

uv run -m tt.main \
get \
simple-transaction \
--symbol TLT

uv run -m tt.main \
get \
simple-transaction \
--symbol AAPL

uv run -m tt.main \
get \
simple-transaction \
--symbol NVDA

uv run -m tt.main \
get \
simple-transaction \
--symbol TSLA
