- original_namespace: meritz
  original_symbol: IVV.AX
  legit_namespace: NYSEARCA
  legit_symbol: IVV
- original_namespace: meritz
  original_symbol: BRK.B.NY
  legit_namespace: NYSE
  legit_symbol: BRK.B
- original_namespace: meritz
  original_symbol: QQQ.OQ
  legit_namespace: NASDAQ
  legit_symbol: QQQ
- original_namespace: kiwoom
  original_symbol: TSLA
  legit_namespace: NASDAQ
  legit_symbol: TSLA
- original_namespace: kiwoom
  original_symbol: IVV
  legit_namespace: NYSEARCA
  legit_symbol: IVV
- original_namespace: kiwoom
  original_symbol: BRKb
  legit_namespace: NYSE
  legit_symbol: BRK.B
- original_namespace: kiwoom
  original_symbol: CPNG
  legit_namespace: NYSE
  legit_symbol: CPNG
- original_namespace: kiwoom
  original_symbol: GOOGL
  legit_namespace: NASDAQ
  legit_symbol: GOOGL
- original_namespace: kiwoom
  original_symbol: NVDA
  legit_namespace: NASDAQ
  legit_symbol: NVDA
- original_namespace: kiwoom
  original_symbol: LCID
  legit_namespace: NASDAQ
  legit_symbol: LCID
- original_namespace: kiwoom
  original_symbol: TQQQ
  legit_namespace: NASDAQ
  legit_symbol: TQQQ
- original_namespace: kiwoom
  original_symbol: JPM
  legit_namespace: NYSE
  legit_symbol: JPM
- original_namespace: kiwoom
  original_symbol: SQQQ
  legit_namespace: NASDAQ
  legit_symbol: SQQQ
- original_namespace: kiwoom
  original_symbol: BAC
  legit_namespace: NYSE
  legit_symbol: BAC
- original_namespace: kiwoom
  original_symbol: USO
  legit_namespace: NYSEARCA
  legit_symbol: USO
- original_namespace: kiwoom
  original_symbol: RISR
  legit_namespace: NYSEARCA
  legit_symbol: RISR
- original_namespace: kiwoom
  original_symbol: PFIX
  legit_namespace: NYSEARCA
  legit_symbol: PFIX
- original_namespace: kiwoom
  original_symbol: PSQ
  legit_namespace: NYSEARCA
  legit_symbol: PSQ
- original_namespace: kiwoom
  original_symbol: TSLS
  legit_namespace: NASDAQ
  legit_symbol: TSLS
- original_namespace: kiwoom
  original_symbol: GLD
  legit_namespace: NYSEARCA
  legit_symbol: GLD
- original_namespace: kiwoom
  original_symbol: AAPL
  legit_namespace: NASDAQ
  legit_symbol: AAPL
- original_namespace: kiwoom
  original_symbol: QQQ
  legit_namespace: NASDAQ
  legit_symbol: QQQ
- original_namespace: kiwoom
  original_symbol: GLDM
  legit_namespace: NYSEARCA
  legit_symbol: GLDM
- original_namespace: kiwoom
  original_symbol: TLT
  legit_namespace: NASDAQ
  legit_symbol: TLT
- original_namespace: kiwoom
  original_symbol: MSFT
  legit_namespace: NASDAQ
  legit_symbol: MSFT
- original_namespace: kiwoom
  original_symbol: VOO
  legit_namespace: NYSEARCA
  legit_symbol: VOO
- original_namespace: kiwoom
  original_symbol: LUMN
  legit_namespace: NYSE
  legit_symbol: LUMN
- original_namespace: kiwoom
  original_symbol: EEV
  legit_namespace: NYSEARCA
  legit_symbol: EEV
- original_namespace: kiwoom
  original_symbol: KORU
  legit_namespace: NYSEARCA
  legit_symbol: KORU
- original_namespace: investing_dot_com
  original_symbol: TSLA
  legit_namespace: NASDAQ
  legit_symbol: TSLA
- original_namespace: investing_dot_com
  original_symbol: IVV
  legit_namespace: NYSEARCA
  legit_symbol: IVV
- original_namespace: investing_dot_com
  original_symbol: BRKb
  legit_namespace: NYSE
  legit_symbol: BRK.B
- original_namespace: investing_dot_com
  original_symbol: CPNG
  legit_namespace: NYSE
  legit_symbol: CPNG
- original_namespace: investing_dot_com
  original_symbol: GOOGL
  legit_namespace: NASDAQ
  legit_symbol: GOOGL
- original_namespace: investing_dot_com
  original_symbol: NVDA
  legit_namespace: NASDAQ
  legit_symbol: NVDA
- original_namespace: investing_dot_com
  original_symbol: LCID
  legit_namespace: NASDAQ
  legit_symbol: LCID
- original_namespace: investing_dot_com
  original_symbol: TQQQ
  legit_namespace: NASDAQ
  legit_symbol: TQQQ
- original_namespace: investing_dot_com
  original_symbol: JPM
  legit_namespace: NYSE
  legit_symbol: JPM
- original_namespace: investing_dot_com
  original_symbol: SQQQ
  legit_namespace: NASDAQ
  legit_symbol: SQQQ
- original_namespace: investing_dot_com
  original_symbol: BAC
  legit_namespace: NYSE
  legit_symbol: BAC
- original_namespace: investing_dot_com
  original_symbol: USO
  legit_namespace: NYSEARCA
  legit_symbol: USO
- original_namespace: investing_dot_com
  original_symbol: RISR
  legit_namespace: NYSEARCA
  legit_symbol: RISR
- original_namespace: investing_dot_com
  original_symbol: PFIX
  legit_namespace: NYSEARCA
  legit_symbol: PFIX
- original_namespace: investing_dot_com
  original_symbol: PSQ
  legit_namespace: NYSEARCA
  legit_symbol: PSQ
- original_namespace: investing_dot_com
  original_symbol: TSLS
  legit_namespace: NASDAQ
  legit_symbol: TSLS
- original_namespace: investing_dot_com
  original_symbol: GLD
  legit_namespace: NYSEARCA
  legit_symbol: GLD
- original_namespace: investing_dot_com
  original_symbol: AAPL
  legit_namespace: NASDAQ
  legit_symbol: AAPL
- original_namespace: investing_dot_com
  original_symbol: QQQ
  legit_namespace: NASDAQ
  legit_symbol: QQQ
- original_namespace: investing_dot_com
  original_symbol: GLDM
  legit_namespace: NYSEARCA
  legit_symbol: GLDM
- original_namespace: investing_dot_com
  original_symbol: TLT
  legit_namespace: NASDAQ
  legit_symbol: TLT
- original_namespace: investing_dot_com
  original_symbol: MSFT
  legit_namespace: NASDAQ
  legit_symbol: MSFT
- original_namespace: investing_dot_com
  original_symbol: VOO
  legit_namespace: NYSEARCA
  legit_symbol: VOO
- original_namespace: investing_dot_com
  original_symbol: LUMN
  legit_namespace: NYSE
  legit_symbol: LUMN
- original_namespace: investing_dot_com
  original_symbol: EEV
  legit_namespace: NYSEARCA
  legit_symbol: EEV
- original_namespace: investing_dot_com
  original_symbol: KORU
  legit_namespace: NYSEARCA
  legit_symbol: KORU
- original_namespace: meritz
  original_symbol: TSLS.OQ
  legit_namespace: NYSEARCA
  legit_symbol: TSLS
- original_namespace: meritz
  original_symbol: NVDA.OQ
  legit_namespace: NASDAQ
  legit_symbol: NVDA
- original_namespace: shinhan
  original_symbol: TSLS
  legit_namespace: NYSEARCA
  legit_symbol: TSLS
- original_namespace: shinhan
  original_symbol: NVDA
  legit_namespace: NASDAQ
  legit_symbol: NVDA
- original_namespace: shinhan
  original_symbol: TSLA
  legit_namespace: NASDAQ
  legit_symbol: TSLA
- original_namespace: kiwoom
  original_symbol: OIL
  legit_namespace: NYSEARCA
  legit_symbol: OILK
- original_namespace: kiwoom
  original_symbol: MU
  legit_namespace: NASDAQ
  legit_symbol: MU
- original_namespace: investing_dot_com
  original_symbol: MU
  legit_namespace: NASDAQ
  legit_symbol: MU
