- user_identifier: user1
  categories:
    - 식비
    - 카페·간식
    - 편의점·마트·잡화
    - 술·유흥
    - 쇼핑
    - 취미·여가
    - 의료·건강·피트니스
    - 주거·통신
    - 보험·세금·기타금융
    - 미용
    - 교통·자동차
    - 여행 상세 식비
    - 여행 상세 숙박
    - 여행 상세 교통
    - 여행 상세 기타
    - 교육
    - 생활
    - 기부·후원
    - 카테고리 없음
    - ATM출금
    - 이체
    - 급여
    - 수입 앱테크
    - 수입 자본이전
    - 수입 기타
    - 수입 배당금
    - 카드대금
    - 저축·투자
    - 후불결제대금
    - 가족 급여
    - 가족 일시급여
    - 가족 병원비
    - 가족 간병비
    - 가족 추가간병비
    - 가족 물품비
    - 가족 기타